# Generated by Django 4.0 on 2021-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnA', models.CharField(max_length=200)),
                ('columnB', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
