# Generated by Django 4.0 on 2021-12-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='columnC',
            field=models.IntegerField(default=0),
        ),
    ]
