# Generated by Django 4.0 on 2021-12-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testdb_columnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdb',
            name='columnC',
        ),
    ]
