# Generated by Django 4.0 on 2021-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_testdb_columnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resJson', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
