# Generated by Django 4.0 on 2021-12-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_response_t_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response_t',
            old_name='url',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='response_t',
            old_name='resJson',
            new_name='data',
        ),
    ]
