name: cloud_run_cicd

on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "static/**"
      - "playlastify/**"
      - "main/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "static/**"
      - "playlastify/**"
      - "main/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: GCP auth
        run: |
          gcloud auth configure-docker
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: build image and push to gcr
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
          gcloud config set run/region asia-east1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: GCP auth
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: deploy gcr image to gcp cloud run
        run: gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}